name: Docker Container for Ubuntu 26.04
on:
  workflow_dispatch:
  push:
permissions:
  contents: read

jobs:
  build:
    uses: n138-kz/Dockerfile.ubuntu/.github/workflows/docker-image_ubuntu2604.yml@main
